---
apiVersion: batch/v1
kind: Job
metadata:
  name: qt-satd-999
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - name: td-worker
        image: s141015/review_td:v1
        imagePullPolicy: Always
        resources:
          requests:
            memory: "16Gi"
            cpu: "3"
        volumeMounts:
          - name: smb
            mountPath: "/data"
            readOnly: false
        command: ["sh", "run.sh", "qt", "72800", "72900", "3"]
      volumes:
        - name: smb
          persistentVolumeClaim:
            claimName: pvc-smb
      restartPolicy: Never